== Data Structures

=== Vectors


+*In[2]:*+
[source, clojure]
----
[1 2 3 4] ; a very simple vector
----


+*Out[2]:*+
----
[1 2 3 4]
----


+*In[36]:*+
[source, clojure]
----
(vector 1 2 3)
----


+*Out[36]:*+
----
[1 2 3]
----


+*In[3]:*+
[source, clojure]
----
[1 true "Bashir"] ; vector containing multiple data types
----


+*Out[3]:*+
----
[1 true "Bashir"]
----


+*In[4]:*+
[source, clojure]
----
(def friends
    ["Ram" "Bashir" "Antony" "Buddha"])
----


+*Out[4]:*+
----#'user/friends----


+*In[5]:*+
[source, clojure]
----
(first friends)
----


+*Out[5]:*+
----
"Ram"
----


+*In[6]:*+
[source, clojure]
----
(rest friends)
----


+*Out[6]:*+
----
("Bashir" "Antony" "Buddha")
----


+*In[8]:*+
[source, clojure]
----
(type friends)
----


+*Out[8]:*+
----
clojure.lang.PersistentVector
----


+*In[9]:*+
[source, clojure]
----
(type (rest friends))
----


+*Out[9]:*+
----
clojure.lang.PersistentVector$ChunkedSeq
----


+*In[10]:*+
[source, clojure]
----
(nth friends 3)
----


+*Out[10]:*+
----
"Buddha"
----


+*In[11]:*+
[source, clojure]
----
(friends 3)
----


+*Out[11]:*+
----
"Buddha"
----


+*In[19]:*+
[source, clojure]
----
(conj friends "Periyaar")
----


+*Out[19]:*+
----
["Ram" "Bashir" "Antony" "Buddha" "Periyaar"]
----


+*In[20]:*+
[source, clojure]
----
(println friends)
----


+*Out[20]:*+
----
[Ram Bashir Antony Buddha]
nil
----


+*In[33]:*+
[source, clojure]
----
(cons "Periyaar" friends)
----


+*Out[33]:*+
----
("Periyaar" "Ram" "Bashir" "Antony" "Buddha")
----

=== Lists


+*In[23]:*+
[source, clojure]
----
'(1 2 3 4)
----


+*Out[23]:*+
----
(1 2 3 4)
----


+*In[37]:*+
[source, clojure]
----
(list 1 2 3)
----


+*Out[37]:*+
----
(1 2 3)
----


+*In[24]:*+
[source, clojure]
----
(list 1 2 3)
----


+*Out[24]:*+
----
(1 2 3)
----


+*In[25]:*+
[source, clojure]
----
(def friends-list
    '("Ram" "Bashir" "Antony" "Buddha"))
----


+*Out[25]:*+
----
#'user/friends-list
----


+*In[26]:*+
[source, clojure]
----
(count friends-list)
----


+*Out[26]:*+
----
4
----


+*In[27]:*+
[source, clojure]
----
(first friends-list)
----


+*Out[27]:*+
----
"Ram"
----


+*In[28]:*+
[source, clojure]
----
(rest friends-list)
----


+*Out[28]:*+
----
("Bashir" "Antony" "Buddha")
----


+*In[29]:*+
[source, clojure]
----
(nth friends-list 3)
----


+*Out[29]:*+
----
"Buddha"
----


+*In[30]:*+
[source, clojure]
----
(friends-list 3)
----


+*Out[30]:*+
----
Execution error (ClassCastException) at user/eval5554 (REPL:1).
clojure.lang.PersistentList cannot be cast to clojure.lang.IFn


       core.clj:  3214 clojure.core$eval/invokeStatic

       core.clj:  3210 clojure.core$eval/invoke

       main.clj:   437 clojure.main$repl$read_eval_print__9086$fn__9089/invoke

       main.clj:   458 clojure.main$repl$fn__9095/invoke

       main.clj:   368 clojure.main$repl/doInvoke

    RestFn.java:  1523 clojure.lang.RestFn/invoke

       AFn.java:    22 clojure.lang.AFn/run

       AFn.java:    22 clojure.lang.AFn/run

    Thread.java:   745 java.lang.Thread/run

----


+*In[32]:*+
[source, clojure]
----
(conj friends-list "Periyaar")
----


+*Out[32]:*+
----
("Periyaar" "Ram" "Bashir" "Antony" "Buddha")
----

=== Maps


+*In[39]:*+
[source, clojure]
----
{ "name" "Bashir" "age" 12 }
----


+*Out[39]:*+
----
{"name" "Bashir", "age" 12}
----


+*In[40]:*+
[source, clojure]
----
(hash-map "name" "Bashir"
          "age" 20)
----


+*Out[40]:*+
----
{"age" 20, "name" "Bashir"}
----


+*In[41]:*+
[source, clojure]
----
(def friend { "name" "Bashir" "age" 12 })
----


+*Out[41]:*+
----
#'user/friend
----


+*In[42]:*+
[source, clojure]
----
(get friend "name")
----


+*Out[42]:*+
----
"Bashir"
----


+*In[43]:*+
[source, clojure]
----
(friend "name")
----


+*Out[43]:*+
----
"Bashir"
----


+*In[44]:*+
[source, clojure]
----
(type "name")
----


+*Out[44]:*+
----
java.lang.String
----


+*In[45]:*+
[source, clojure]
----
(type :name)
----


+*Out[45]:*+
----
clojure.lang.Keyword
----


+*In[47]:*+
[source, clojure]
----
(def wise-friend {:name "Periyaar"
                  :age 90})
----


+*Out[47]:*+
----
#'user/wise-friend
----


+*In[48]:*+
[source, clojure]
----
(wise-friend :name)
----


+*Out[48]:*+
----
"Periyaar"
----


+*In[49]:*+
[source, clojure]
----
(get wise-friend :age)
----


+*Out[49]:*+
----
90
----


+*In[55]:*+
[source, clojure]
----
(print (wise-friend :name)
       "is very wise.")
----


+*Out[55]:*+
----
Periyaar is very wise.nil
----


+*In[56]:*+
[source, clojure]
----
(assoc wise-friend :belief "Rationalism")
----


+*Out[56]:*+
----
{:name "Periyaar", :age 90, :belief "Rationalism"}
----


+*In[57]:*+
[source, clojure]
----
(wise-friend :belief)
----


+*Out[57]:*+
----nil----


+*In[59]:*+
[source, clojure]
----
(wise-friend :age)
----


+*Out[59]:*+
----90----


+*In[60]:*+
[source, clojure]
----
(dissoc wise-friend :age)
----


+*Out[60]:*+
----
{:name "Periyaar"}
----


+*In[61]:*+
[source, clojure]
----
(keys wise-friend)
----


+*Out[61]:*+
----
(:name :age)
----


+*In[62]:*+
[source, clojure]
----
(vals wise-friend)
----


+*Out[62]:*+
----
("Periyaar" 90)
----


+*In[82]:*+
[source, clojure]
----
(assoc wise-friend "name" "Ramasamy")
----


+*Out[82]:*+
----
{:name "Periyaar", :age 90, "name" "Ramasamy"}
----

=== Sets


+*In[63]:*+
[source, clojure]
----
#{1 2 3 4}
----


+*Out[63]:*+
----
#{1 4 3 2}
----


+*In[64]:*+
[source, clojure]
----
(type #{1 2 3 4})
----


+*Out[64]:*+
----
clojure.lang.PersistentHashSet
----


+*In[65]:*+
[source, clojure]
----
#{1 2 3 4 4}
----


+*Out[65]:*+
----
Syntax error reading source at (REPL:1:13).
Duplicate key: 4


    PersistentHashSet.java:    68 clojure.lang.PersistentHashSet/createWithCheck

           LispReader.java:  1366 clojure.lang.LispReader$SetReader/invoke

           LispReader.java:   853 clojure.lang.LispReader$DispatchReader/invoke

           LispReader.java:   285 clojure.lang.LispReader/read

                  core.clj:  3768 clojure.core$read/invokeStatic

                  core.clj:  3741 clojure.core$read/invoke

                  main.clj:   433 clojure.main$repl$read_eval_print__9086$fn__9087/invoke

                  main.clj:   432 clojure.main$repl$read_eval_print__9086/invoke

                  main.clj:   458 clojure.main$repl$fn__9095/invoke

                  main.clj:   368 clojure.main$repl/doInvoke

               RestFn.java:  1523 clojure.lang.RestFn/invoke

                  AFn.java:    22 clojure.lang.AFn/run

                  AFn.java:    22 clojure.lang.AFn/run

               Thread.java:   745 java.lang.Thread/run

----


+*In[66]:*+
[source, clojure]
----
#{"Apple" "Orange" "Mango" "Banana"}
----


+*Out[66]:*+
----
#{"Mango" "Orange" "Apple" "Banana"}
----


+*In[67]:*+
[source, clojure]
----
#{"Apple" "Orange" "Mango" "Banana" "Apple"}
----


+*Out[67]:*+
----
Syntax error reading source at (REPL:1:45).
Duplicate key: Apple


    PersistentHashSet.java:    68 clojure.lang.PersistentHashSet/createWithCheck

           LispReader.java:  1366 clojure.lang.LispReader$SetReader/invoke

           LispReader.java:   853 clojure.lang.LispReader$DispatchReader/invoke

           LispReader.java:   285 clojure.lang.LispReader/read

                  core.clj:  3768 clojure.core$read/invokeStatic

                  core.clj:  3741 clojure.core$read/invoke

                  main.clj:   433 clojure.main$repl$read_eval_print__9086$fn__9087/invoke

                  main.clj:   432 clojure.main$repl$read_eval_print__9086/invoke

                  main.clj:   458 clojure.main$repl$fn__9095/invoke

                  main.clj:   368 clojure.main$repl/doInvoke

               RestFn.java:  1523 clojure.lang.RestFn/invoke

                  AFn.java:    22 clojure.lang.AFn/run

                  AFn.java:    22 clojure.lang.AFn/run

               Thread.java:   745 java.lang.Thread/run

----


+*In[68]:*+
[source, clojure]
----
(def fruits #{"Apple" "Orange" "Mango" "Banana"})
----


+*Out[68]:*+
----
#'user/fruits
----


+*In[69]:*+
[source, clojure]
----
(contains? fruits "Banana")
----


+*Out[69]:*+
----
true
----


+*In[70]:*+
[source, clojure]
----
(contains? fruits "Jack Fruit")
----


+*Out[70]:*+
----
false
----


+*In[71]:*+
[source, clojure]
----
(fruits "Banana")
----


+*Out[71]:*+
----
"Banana"
----


+*In[72]:*+
[source, clojure]
----
(fruits "Jack Fruit")
----


+*Out[72]:*+
----
nil
----


+*In[73]:*+
[source, clojure]
----
("Banana" fruits)
----


+*Out[73]:*+
----
Execution error (ClassCastException) at user/eval5624 (REPL:1).
java.lang.String cannot be cast to clojure.lang.IFn


       core.clj:  3214 clojure.core$eval/invokeStatic

       core.clj:  3210 clojure.core$eval/invoke

       main.clj:   437 clojure.main$repl$read_eval_print__9086$fn__9089/invoke

       main.clj:   458 clojure.main$repl$fn__9095/invoke

       main.clj:   368 clojure.main$repl/doInvoke

    RestFn.java:  1523 clojure.lang.RestFn/invoke

       AFn.java:    22 clojure.lang.AFn/run

       AFn.java:    22 clojure.lang.AFn/run

    Thread.java:   745 java.lang.Thread/run

----


+*In[74]:*+
[source, clojure]
----
(def programming-languages #{:ruby :python :clojure})
----


+*Out[74]:*+
----
#'user/programming-languages
----


+*In[75]:*+
[source, clojure]
----
(contains? programming-languages :ruby)
----


+*Out[75]:*+
----
true
----


+*In[76]:*+
[source, clojure]
----
(contains? programming-languages :java)
----


+*Out[76]:*+
----false----


+*In[77]:*+
[source, clojure]
----
(programming-languages :ruby)
----


+*Out[77]:*+
----
:ruby
----


+*In[78]:*+
[source, clojure]
----
(:ruby programming-languages)
----


+*Out[78]:*+
----
:ruby
----


+*In[80]:*+
[source, clojure]
----
(conj programming-languages :perl)
----


+*Out[80]:*+
----
#{:clojure :python :perl :ruby}
----


+*In[81]:*+
[source, clojure]
----
(disj programming-languages :perl)
----


+*Out[81]:*+
----
#{:clojure :python :ruby}
----


