=== filter

`filter` collects and returns value of a sequence that when passed to a function returns `true`. For example `(odd? 1)` returns `true`, whereas `(odd? 1)` returns `false`. Look at the code bel,ow:

[source, clojure]
----
(filter odd? (range 1 11))
----

Output

----
(1 3 5 7 9)
----

We have `filter`, as it's first argument we pass `odd?`, and as a second argument we pass numbers from 1 to 10 which is generated by `(range 1 11)`. Which ever number makes `odd?` `true` s caught by the `filter` and is returned out.

In the same way below, even numbers are returned:

[source, clojure]
----
(filter even? (range 1 11))
----

Output

----
(2 4 6 8 10)
----

In the code below:

[source, clojure]
----
(filter #(> % 5) (range 1 11))
----

Output

----
(6 7 8 9 10)
----

to the `filter`, we pass a anonymous function `\#()` who's argument `\#(%)` should be greater `\#(> %)` than 5 `#(> % 5)`. And all numbers greater than 5, between 1 and 10 is returned out in the above example.

In the example below, all numbers from 1 to 10, that are less lan 5 is returned out: 

[source, clojure]
----
(filter #(> 5 %) (range 1 11))
----

Output

----
(1 2 3 4)
----

[source, clojure]
----
(filter (fn [x] (> x 5)) (range 1 11))
----

Output

----
(6 7 8 9 10)
----

In the code below I define a function called `greater-than-5`, which returns true if a number is greater than 5:

[source, clojure]
----
(defn greater-than-5 [x]
  (> x 5))
----

Output

----
#'user/greater-than-5
----

I use it with `filter` to find numbers that are greater than 5 as shown below:

[source, clojure]
----
(filter greater-than-5 (range 1 11))
----

Output

----
(6 7 8 9 10)
----
