== Functions

Abstraction is the key to greatness and progress. Michael Faraday discovered electricity and magnetism have a link, but I don't think about it when I drive my car. Everything is abstracted away behind the steering wheel and pedals. Abstraction is so important, that almost every programming language provides a way to abstract away complexity.

Functions are the way you can abstract away things in Clojure. Whenever a code gets complex, you can refactor it out as functions, and use those functions as building blocks. In fact, you have been using functions all along, say when you call `(+ 1 2)` in Clojure, the `+` is a function, and `1` and `2` are the value it receives. Technically we call the values received by the function as arguments. You really not worried or don't know what happens in computer when you execute `(+ 1 2)`, it's been neatly abstracted away behind the function `+`.

So let's see how to build our own functions in this chapter.

include::saying_hello_with_functions.adoc[]

include::passing_Arguments.adoc[]

include::refactoring.adoc[]

include::functions_with_multiple_arguments.adoc[]

include::accepting_unlimitted_arguments.adoc[]

include::returning_stuff.adoc[]

include::recursion.adoc[]

include::multimethods.adoc[]

include::pre_and_post_condition_checking.adoc[]

include::docstring.adoc[]

include::anonymous_functions.adoc[]

include::functions_returning_functions.adoc[]
