=== cycle

:file-name: lazy_sequence_cycle.clj

include::use_code_note.adoc[]

Let's say you want to go through a sequence in a cyclical manner, then `cycle`is the function to use. Take a look at the code below:

[source, clojure]
----
(def multiverse (cycle ["universe" "antiverse"]))
----

Output

----
#'user/multiverse
----

The above code theoretically creates an infinite list, attaches it to a variable `multiverse` where every odd element is `"universe"` and every even element is `"antiverse"`. So the first element would be `"universe"`:

[source, clojure]
----
(first multiverse)
----

Output

----
"universe"
----

the second would be `"antiverse"`:

[source, clojure]
----
(second multiverse)
----

Output

----
"antiverse"
----

If we take 5 of it, it would alternate between `"universe"` and `"antiverse"` as shown:

[source, clojure]
----
(take 5 multiverse)
----

Output

----
("universe" "antiverse" "universe" "antiverse" "universe")
----

We can take any `nth` odd element, and it's going to be `"universe"`:

[source, clojure]
----
(nth multiverse 2000)
----

Output

----
"universe"
----

Similarly, any `nth` even element is going to be `"antiverse"`:

[source, clojure]
----
(nth multiverse 1783)
----

Output

----
"antiverse"
----

Now let's cycle some South Indian tiffin items: 

[source, clojure]
----
(def tiffin-items
  (cycle ["idli", "vadai", "dosai", "sambar"]))
----

Output

----
#'user/tiffin-items
----

Let's take the 6th element:

[source, clojure]
----
(nth tiffin-items 5)
----

Output

----
"vadai"
----

So the last element `"sambar"` is indexed 3, and hence the 0^th^ element behaves like 5^th^ and the 1^st^ element behaves like 6^th^, like a never ending loop. 


Now let's take 10 `tiffin-items`, see ow it repeats again and again:

[source, clojure]
----
(take 10 tiffin-items)
----

Output

----
("idli" "vadai" "dosai" "sambar" "idli" "vadai" "dosai" "sambar" "idli" "vadai")
----
