=== map

Let's say you have a function that acts on an argument, say `inc`, `(inc 1)` gives 2. Now if I want to make the `inc` work on a collection or sequence, how do I do it? Simple, pass it to the `map`, then followed by collection as shown: 

[source, clojure]
----
(map inc [1 2 3])
----

Output

----
(2 3 4)
----

As you can see in the above case `map` makes each element in `[1 2 3]` be acted on by the inc method, collects the output in a  list and returns it. So you get `(2 3 4)` as output.

In the case below I pass an anonymous function `(fn [x] (+ x 1))` to `map` and make it act upon `[1 2 3]`:

[source, clojure]
----
(map (fn [x] (+ x 1)) [1 2 3])
----

Output

----
(2 3 4)
----

It works just fine, it's just to show that you need not have a predefined function and in Clojure you can build small functions just like that.

Execute the code below, it works same as the previous examples above:

[source, clojure]
----
(map #(+ % 1) [1 2 3])
----

Output

----
(2 3 4)
----

There is another way to write anonymous function `(fn [x] (+ x 1))`, it can be written as `\#(+ % 1)`. You can define the function content between `#()`, the `%` signifies the argument been passed to the function, and we want to add 1 to it, so it becomes `#(+ % 1)`. Isn't this more better than `(fn [x] (+ x 1))`?

Let's say we have a function that takes two arguments as shown:

[source, clojure]
----
(fn [x y]
  (+ (Math/pow x 2)
    (Math/pow y 2)))
----

In tha above case the function takes two arguments and returns it's sun of squares. Now how to make this function work with sequence? Simple pass it to map as shown:


[source, clojure]
----
(map (fn [x y]
       (+ (Math/pow x 2)
          (Math/pow y 2))))
----

Next pass the sequence for the first argument, in this case it's `x`:

[source, clojure]
----
(map (fn [x y]
       (+ (Math/pow x 2)
          (Math/pow y 2))) [1 2 3])
----


Next pass the sequence for the second argument, in this case its `y`:

[source, clojure]
----
(map (fn [x y]
       (+ (Math/pow x 2)
          (Math/pow y 2))) [1 2 3] [2 3 4])
----

Output

----
(5.0 13.0 25.0)
----

So the above code works as follows, `map` takes the first element from `[1 2 3]`, it's `1` in this case and the first element from `[2 3 4]`, it's `2` in this case and passes it to:

[source, clojure]
----
(fn [x y]
  (+ (Math/pow x 2)
    (Math/pow y 2)))
----

So this function suns and squares it and returns it as `5.0`, the map collects it in a list and it becomes `(5.0)`.

Then `map` take the second argument from `[1 2 3]` which is `2`, and `[2 3 4]` which is `3` and passes it to the function, and the function returns `13.0`, which is appended to the list making it `(5.0 13.0)`, similarly the same is performed on third arguments of the passed sequences and the result `25.0` is appended to the list and it becomes `(5.0 13.0 25.0)`, this final list is returned out.

In the esample below I have a function called sum-of-squares:

[source, clojure]
----
(defn sum-of-squares [x y]
  (+ (Math/pow x 2)
     (Math/pow y 2)))
----

Which is nothing but giving a name to this anonymous function:

[source, clojure]
----
(fn [x y]
  (+ (Math/pow x 2)
    (Math/pow y 2)))
----

we had used previously. We use the name `sum-of-squares` with map and pass two sequences for `x` and `y` and get the same result as shown below:

[source, clojure]
----
(map sum-of-squares [1 2 3] [2 3 4])
----

Output

----
(5.0 13.0 25.0)
----

Below I have defined a function called `double-it`, which doubles the number passed:

[source, clojure]
----
(defn double-it [x]
  (* x 2))
----

Output

----
#'user/double-it
----

I ise it in map to double the numbers in a vector:

[source, clojure]
----
(map double-it [1 2 3])
----

Output

----
(2 4 6)
----

