=== Passing Argument

We can pass arguments to functions, say we have a function stem:[f(x) = x^2 + 2], this function accepts an argument stem:[x], now we plug in 7 to x, then stem:[f(7) = 51]. In the same way, a programming function can take in argument and do something with it.

Look at the say hello example below, type iit and execute it:

[source, clojure]
----
;; function_with_arguments.clj

(defn say-hello [name]
  (println "Hello" name "!"))

(say-hello "Karthik")
----

Output

----
Hello Karthik !
nil
----

It prints `Hello Karthik !`, so how it works? We `(defn say-hello ...)`, where we define a function named `say-hello`, bu then after that notice the `[name]` as shown below:

[source, clojure]
----
(defn say-hello [name]
  ;; function body goes here
  )
----

The `name` is an argument you need to pass for the function to run. It an be used as variable in the function. Notice how the function is structured, you have the `defn`, followed by the function name then there the square bracket containing the sigle argument name `[name]`. Now let's finish off the function by writing its body as shown:

[source, clojure]
----
(defn say-hello [name]
  (println "Hello" name "!"))
----

As function body, we are just printing saying hello to the `name` passed using `println` like this: `(println "Hello" name "!")`.

Now calling `say-hello` with argument `Karthik` `(say-hello "Karthik")` prints out `Hello Karthik !`. Modify the program to say hello to you.

=== Finding Area Of Circle

We know that area of circle is stem:[pi r^2], given radius of a circle is stored in a variable `radius`, we can write a Clojure code to find area as shown:

[source, clojure]
----
(* Math/PI (Math/pow radius 2))
----

Now, rather than writing as above, won't it be good if we can find area of circle by calling a function `circle-area`? That's what we do in code below: 


[source, clojure]
----
;; function_circle_area.clj

(defn circle-area [radius]
  (* Math/PI (Math/pow radius 2)))

(circle-area 7)
----

Output

----
153.93804002589985
----

In the above code, rather than dealing with `Math/PI` and finding power, all we need to do is to call `(circle-area 7)`, and we get the area of circle whose radius is 7 units. A good function abstracts complexity away and makes us write programs better and better.