== Records and Protocols

If you want to learn records and protocols watching video's here is one https://www.youtube.com/watch?v=xpH6RGjZwNg.

Clojure came during an era when Object Oriented Programming (OOP) was at a peak, then, due to large code bases OOP started to failed and people started looking into functional programming. So I find it not surprising that Clojure gives some ways to create objects and do stuff with them.

In Clojure Object is nothing but a glorified map, and nothing more. You may not use it, but you can.


=== Creating objects

:file-name: record.clj

include::use_code_note.adoc[]

Objects are called Records in Clojure, so let's create our first record called `Car` which would hold the `name` and `top-speed` of the car as shown: 

[source, clojure]
----
(defrecord Car [name top-speed])
----

Output

----
user.Car
----

As you see from the output this creates something called `user.Car`. User is the default namespace, and I think `.Car` represents the record. If `Car` was just a variable, we would have got an output like `user/Car`.

Now let's define a variable called `tata-nano`:

[source, clojure]
----
(def tata-nano)
----

Of the the type car:

[source, clojure]
----
(def tata-nano (->Car))
----

While we created record `Car`, the first thing we specified was `name` and then `top-speed`, so in that same order, let's give a name for `tata-nano`

[source, clojure]
----
(def tata-nano (->Car "Tata Nano"))
----

And specify it's top speed as `120`:

[source, clojure]
----
(def tata-nano (->Car "Tata Nano" 120))
----

Let's now execute the code above:

[source, clojure]
----
(def tata-nano (->Car "Tata Nano" 120))
----

Output

----
#'user/tata-nano
----

So a variable `tata-nano` is created in `user` namespace, this is not a simple value, but an object containing two values.

Object is a glorified hash in Clojure, so you can access `:name` of `tata-nano` just like you do with a has as shown:

[source, clojure]
----
(:name tata-nano)
----

Output

----
"Tata Nano"
----

[source, clojure]
----
(get tata-nano :name)
----

Output

----
"Tata Nano"
----

Similarly you can access it's top speed:

[source, clojure]
----
(:top-speed tata-nano)
----

Output

----
120
----

[source, clojure]
----
(get tata-nano :top-speed)
----

Output

----
120
----

Similarly let me create another record instance of `Car` called `ambassador`, but there is difference in code below: 

[source, clojure]
----
(def ambassador (map->Car {:name "Ambassador",
                           :top-speed 240 }))
----

Output

----
#'user/ambassador
----

While creating `tata-nano`, we gave values it must hold in a positional way, but look at `map->Car`, instead of `->Car` in the code above, here we saying we want to pass a map so we pass this map:

[source, clojure]
----
{ :name "Ambassador",
  :top-speed 240 }
----

And Clojure is smart enough to un-bundle it, and put the right values in right variables of `ambassador`. You can also vary the position like shown:

[source, clojure]
----
{ :top-speed 240
  :name "Ambassador" }
----

It will still work the same. 

Let's now get the `:name` and `:top-speed` of ambassador:

[source, clojure]
----
(:name ambassador)
----

Output

----
"Ambassador"
----

[source, clojure]
----
(get ambassador :name)
----

Output

----
"Ambassador"
----

[source, clojure]
----
(:top-speed ambassador)
----

Output

----
240
----

[source, clojure]
----
(get ambassador :top-speed)
----

Output

----
240
----

=== Using objects with functions

:file-name: record_2.clj

include::use_code_note.adoc[]

[source, clojure]
----
(defrecord Car [name top-speed])
----

Output

----
user.Car
----

[source, clojure]
----
(def tata-nano (->Car "Tata Nano" 120))
----

Output

----
#'user/tata-nano
----

[source, clojure]
----
(defn describe [vehicle]
  (let [{name :name top-speed :top-speed} vehicle]
    (str name " has a top speed of " top-speed "Km/hr.")))
----

Output

----
#'user/describe
----

[source, clojure]
----
(describe tata-nano)
----

Output

----
"Tata Nano has a top speed of 120Km/hr."
----

[source, clojure]
----
(defrecord Ship [name top-speed])
----

Output

----
user.Ship
----

[source, clojure]
----
(def artic-explorer (->Ship "Artic Explorer" 10))
----

Output

----
#'user/artic-explorer
----

[source, clojure]
----
(defn describe-ship [vehicle]
  (let [{name :name top-speed :top-speed} vehicle]
    (str name " has a top speed of " top-speed " knots.")))
----

Output

----
#'user/describe-ship
----

[source, clojure]
----
(describe-ship artic-explorer)
----

Output

----
"Artic Explorer has a top speed of 10 knots."
----

=== Protocols

:file-name: protocol.clj

include::use_code_note.adoc[]

[source, clojure]
----
(defprotocol Describe
  (describe [this]))
----

Output

----
Describe
----

[source, clojure]
----
(defrecord Car [name top-speed]
  Describe
  (describe [this]
    (let [{name :name top-speed :top-speed} this]
      (str name " has a top speed of " top-speed "Km/hr."))))
----

Output

----
user.Car
----

[source, clojure]
----
(defrecord Ship [name top-speed]
  Describe
  (describe [this]
    (let [{name :name top-speed :top-speed} this]
      (str name " has a top speed of " top-speed " knots."))))
----

Output

----
user.Ship
----

[source, clojure]
----
(def tata-nano (->Car "Tata Nano" 120))
----

Output

----
#'user/tata-nano
----

[source, clojure]
----
(def artic-explorer (->Ship "Artic Explorer" 10))
----

Output

----
#'user/artic-explorer
----

[source, clojure]
----
(describe tata-nano)
----

Output

----
"Tata Nano has a top speed of 120Km/hr."
----

[source, clojure]
----
(describe artic-explorer)
----

Output

----
"Artic Explorer has a top speed of 10 knots."
----

:file-name: extend-protocol.clj

include::use_code_note.adoc[]

[source, clojure]
----
(defprotocol Describe
  (describe [this]))
----

Output
----

----

[source, clojure]
----
(defrecord Car [name top-speed]
  Describe
  (describe [this]
    (let [{name :name top-speed :top-speed} this]
      (str name " has a top speed of " top-speed "Km/hr."))))
----

Output
----

----

[source, clojure]
----
(def tata-nano (->Car "Tata Nano" 120))
----

Output
----

----

[source, clojure]
----
(describe tata-nano)
----

Output
----

----

[source, clojure]
----
(defrecord Rocket [name orbit])
----

Output
----

----

[source, clojure]
----
(extend-protocol Describe
  Rocket
   (describe [this] (str (:name this) " reaches " (:orbit this) " orbit.")))
----

Output
----

----

[source, clojure]
----
(def pslv (->Rocket "PSLV" "Low Earth"))
----

Output
----

----

[source, clojure]
----
(describe pslv)
----

Output
----

----

