== Records and Protocols

If you want to learn records and protocols watching video's, here is one https://www.youtube.com/watch?v=xpH6RGjZwNg.

Clojure came during an era when Object-Oriented Programming (OOP) was at a peak, then, due to large code bases OOP started to fail and people started looking into functional programming. So I find it not surprising that Clojure gives some ways to create objects and do stuff with them.

In Clojure Object is nothing but a glorified map, and nothing more. You may not use it, but you can.

=== Creating objects

:file-name: record.clj

include::use_code_note.adoc[]

Objects are called Records in Clojure, so let's create our first record called `Car` which would hold the `name` and `top-speed` of the car as shown: 

[source, clojure]
----
(defrecord Car [name top-speed])
----

Output

----
user.Car
----

As you see from the output this creates something called `user.Car`. `user` is the default namespace, and I think `.Car` represents the record. If `Car` was just a variable, we would have got an output like `user/Car`.

Now let's define a variable called `tata-nano`:

[source, clojure]
----
(def tata-nano)
----

Of the type `Car`:

[source, clojure]
----
(def tata-nano (->Car))
----

While we created record `Car`, the first thing we specified was `name` and then `top-speed`, so in that same order, let's give a name for `tata-nano`

[source, clojure]
----
(def tata-nano (->Car "Tata Nano"))
----

And specify it's top speed as `120`:

[source, clojure]
----
(def tata-nano (->Car "Tata Nano" 120))
----

Let's now execute the code above:

[source, clojure]
----
(def tata-nano (->Car "Tata Nano" 120))
----

Output

----
#'user/tata-nano
----

So a variable `tata-nano` is created in `user` namespace, this is not a simple value, but an object containing two values.

Object is a glorified map in Clojure, so you can access `:name` of `tata-nano` just like you do with a map as shown:

[source, clojure]
----
(:name tata-nano)
----

Output

----
"Tata Nano"
----

[source, clojure]
----
(get tata-nano :name)
----

Output

----
"Tata Nano"
----

Similarly, you can access it's top speed:

[source, clojure]
----
(:top-speed tata-nano)
----

Output

----
120
----

[source, clojure]
----
(get tata-nano :top-speed)
----

Output

----
120
----

Similarly, let me create another record instance of `Car` called `ambassador`, but there is difference in code below: 

[source, clojure]
----
(def ambassador (map->Car {:name "Ambassador",
                           :top-speed 240 }))
----

Output

----
#'user/ambassador
----

While creating `tata-nano`, we gave values it must hold in a positional way, but look at `map->Car`, instead of `->Car` in the code above, here we are saying we want to pass a map, so we pass this map:

[source, clojure]
----
{ :name "Ambassador",
  :top-speed 240 }
----

And Clojure is smart enough to unpack it, and put the right values in right variables of `ambassador`. You can also vary the position like shown:

[source, clojure]
----
{ :top-speed 240
  :name "Ambassador" }
----

It still works the same. 

Let's now get the `:name` and `:top-speed` of ambassador:

[source, clojure]
----
(:name ambassador)
----

Output

----
"Ambassador"
----

[source, clojure]
----
(get ambassador :name)
----

Output

----
"Ambassador"
----

[source, clojure]
----
(:top-speed ambassador)
----

Output

----
240
----

[source, clojure]
----
(get ambassador :top-speed)
----

Output

----
240
----

=== Using Records with functions

:file-name: record_2.clj

include::use_code_note.adoc[]

Records can be passed to functions that knows how to handle it. Below we create a record called `Car`.

[source, clojure]
----
(defrecord Car [name top-speed])
----

Output

----
user.Car
----

We create a variable named `tata-nano` which is an instance of `Car`:

[source, clojure]
----
(def tata-nano (->Car "Tata Nano" 120))
----

Output

----
#'user/tata-nano
----

We now code a function that can work with the record, let's name it as `describe`:

[source, clojure]
----
(defn describe [vehicle]
  (let [{name :name top-speed :top-speed} vehicle]
    (str name " has a top speed of " top-speed "Km/hr.")))
----

Output

----
#'user/describe
----

If you see `describe`, it accepts an argument named `vehicle`, let's look at the body of the function:

[source, clojure]
----
(let [{name :name top-speed :top-speed} vehicle]
    (str name " has a top speed of " top-speed "Km/hr."))
----

If you see we are destructing car in `let [{name :name top-speed :top-speed} vehicle]`, in this code snippet, `:name` of the passed `Car` record is assigned to variable `name` and `:top-speed` is assigned to variable `top-speed`. All we have to do now is to return out a beautifully formatted string that describes the car, which is done using this `(str name " has a top speed of " top-speed "Km/hr.")` piece of code, which embeds `name` and `top-speed` into a description string.

Now let's use the `describe` on instance of `Car`:

[source, clojure]
----
(describe tata-nano)
----

Output

----
"Tata Nano has a top speed of 120Km/hr."
----

now let's create a new record called `Ship`

[source, clojure]
----
(defrecord Ship [name top-speed])
----

Output

----
user.Ship
----

Let's create a new ship instance called `arctic-explorer`:

[source, clojure]
----
(def arctic-explorer (->Ship "Arctic Explorer" 10))
----

Output

----
#'user/arctic-explorer
----

Let's write a function called `describe-ship`, that describes a ship:

[source, clojure]
----
(defn describe-ship [vehicle]
  (let [{name :name top-speed :top-speed} vehicle]
    (str name " has a top speed of " top-speed " knots.")))
----

Output

----
#'user/describe-ship
----

Let's use `describe-ship` on `arctic-explorer`

[source, clojure]
----
(describe-ship arctic-explorer)
----

Output

----
"Arctic Explorer has a top speed of 10 knots."
----

It works!

=== Protocols

:file-name: protocol.clj

include::use_code_note.adoc[]

In last section we saw a way to describe about a `Car` using `describe`, and describe a ship using `describe-ship` function. Won't it be great for a programmer if he could just use one `describe` function to describe about a `Ship` and a `Car`? We will see how to do this with protocols here.

So let's create a protocol called `Describe` as shown:

[source, clojure]
----
(defprotocol Describe
  (describe [this]))
----

Output

----
Describe
----

Now look at the code below:

[source, clojure]
----
(defrecord Car [name top-speed]
  Describe
  (describe [this]
    (let [{name :name top-speed :top-speed} this]
      (str name " has a top speed of " top-speed "Km/hr."))))
----

Output

----
user.Car
----

In it we create a record called car:

[source, clojure]
----
(defrecord Car [name top-speed])
----

Next we specify the `Describe` protocol in it:

[source, clojure]
----
(defrecord Car [name top-speed]
  Describe)
----

Then we write the definition of `describe` function for the `Car`:

[source, clojure]
----
(defrecord Car [name top-speed]
  Describe
  (describe [this]
    (let [{name :name top-speed :top-speed} this]
      (str name " has a top speed of " top-speed "Km/hr."))))
----

Note how there is no `defn` above. It just has the function name `describe`, followed by argument `this`, and in the body of describe we destructure `this` and return a string description.

The `this` in examples in this section is not a special keyword that needs to be used in Clojure, it is just name given to a variable, that's it.

Similar for `Ship`, we write a `describe` function as shown:

[source, clojure]
----
(defrecord Ship [name top-speed]
  Describe
  (describe [this]
    (let [{name :name top-speed :top-speed} this]
      (str name " has a top speed of " top-speed " knots."))))
----

Output

----
user.Ship
----

Now let's create a instance of `Car` called `tata-nano`:

[source, clojure]
----
(def tata-nano (->Car "Tata Nano" 120))
----

Output

----
#'user/tata-nano
----

Let's create instance of `Ship` called `arctic-explorer`:

[source, clojure]
----
(def arctic-explorer (->Ship "Arctic Explorer" 10))
----

Output

----
#'user/arctic-explorer
----

When we pass `tata-nano` to the `describe`, it knows its of type `Car` and the `describe` defined in `Car` is called:

[source, clojure]
----
(describe tata-nano)
----

Output

----
"Tata Nano has a top speed of 120Km/hr."
----

Similarly it knows `arctic-explorer` is a ship, and `Ship`'s own `describe` is called in the code below:

[source, clojure]
----
(describe arctic-explorer)
----

Output

----
"Arctic Explorer has a top speed of 10 knots."
----

==== Extend Protocol

:file-name: extend-protocol.clj

include::use_code_note.adoc[]

So we have a protocol `Describe`

[source, clojure]
----
(defprotocol Describe
  (describe [this]))
----

Output

----
Describe
----

We use it to write a function called `describe` for record `Car``

[source, clojure]
----
(defrecord Car [name top-speed]
  Describe
  (describe [this]
    (let [{name :name top-speed :top-speed} this]
      (str name " has a top speed of " top-speed "Km/hr."))))
----

Output

----
user.Car
----

And it works:

[source, clojure]
----
(def tata-nano (->Car "Tata Nano" 120))
----

Output

----
#'user/tata-nano
----

[source, clojure]
----
(describe tata-nano)
----

Output
----
"Tata Nano has a top speed of 120Km/hr.
----

Let's say we have code written by some one else and it's about `Rocket`, and we don't want to mess up the code with our describe, but we want to extend the protocol `Describe` for it.

[source, clojure]
----
(defrecord Rocket [name orbit])
----

Output

----
user.Rocket
----

Well, for that Clojure provides a function called `extend-protocol` that can used to extend the protocol `Describe` as shown below:

[source, clojure]
----
(extend-protocol Describe
  Rocket
   (describe [this] (str (:name this) " reaches " (:orbit this) " orbit.")))
----

Output

----
nil
----

In the code above we say we want to extend protocol

[source, clojure]
----
(extend-protocol)
----

We say that we want to extend `Describe` and we pass it as first argument:

[source, clojure]
----
(extend-protocol Describe)
----

As a second argument we say we want to extend describe for record `Rocket`

[source, clojure]
----
(extend-protocol Describe
  Rocket)
----

and finally we define the `describe` function

[source, clojure]
----
(extend-protocol Describe
  Rocket
   (describe [this] (str (:name this) " reaches " (:orbit this) " orbit.")))
----

Now let's create a `Rocket` called `pslv`

[source, clojure]
----
(def pslv (->Rocket "PSLV" "Low Earth"))
----

Output

----
#'user/pslv
----

Let's pass it to `describe`:

[source, clojure]
----
(describe pslv)
----

Output

----
"PSLV reaches Low Earth orbit."
----

It works!
