=== Strings

:file-name: strings.clj

include::use_code_note.adoc[]

In this book I think your very first clojure program would have been this:

[source, clojure]
----
(println "Hello World!")
----

It prints `Hello World` on the screen. The `"Hello World!"` which is enclosed by double quoted `"` is nothing but a string of characters and hence its called a string.

anything that's enclosed by double quotes in Clojure is a String as you can see below:

[source, clojure]
----
(type "Hello")
----

Output

----
java.lang.String
----

Strings can be joined with even non String things using `str` function as shown: 

[source, clojure]
----
(str "1 + 2 is " (+ 1 2))
----

Output

----
"1 + 2 is 3"
----

In the above code `(+ 1 2)` returns Long, but it can be joined with a string `"1 + 2 is "` by passing them both to  `str` function.

You can get the character count in a string using using the `count` function as shown below:

[source, clojure]
----
(count "Hello")
----

Output

----
5
----

In the code below, to `str` function we are passing 6 arguments. the first five are numbers , and the last one is a string `" and so on..."`:

[source, clojure]
----
(str 1 2 3 4 5 " and so on...")
----

Output

----
"12345 and so on..."
----

You can see how Clojure neatly concatenates them and returns out a string.

Clojure has a inbuilt String library, you can read it's documentation here https://clojuredocs.org/clojure.string. From it let's use the function `reverse` to reverse a String:

[source, clojure]
----
(clojure.string/reverse "Hello")
----

Output

----
"olleH"
----

Now let's covert all characters to upper case: 

[source, clojure]
----
(clojure.string/upper-case "Hello")
----

Output

----
"HELLO"
----

I hope this section has briefly explained something about strings. You wil learn more as you go by. Hang on....
