=== Types of Numbers

:file-name: types_of_numbers.clj

include::use_code_note.adoc[]

There are different types of numbers in computing just like there are different types of numbers in Mathematics. For example whole numbers are called as Long in Clojure. You can verify it by passing a whole number to a function named `type` which tells the type of data been passes to it as shown below:

[source, clojure]
----
(type 147)
----

Output

----
java.lang.Long
----

The numbers with decimal value are called as Double in Clojure as you can see below:

[source, clojure]
----
(type 147.67)
----

Output

----
java.lang.Double
----

The value of stem:[pi] too is a double in Clojure:

[source, clojure]
----
(type Math/PI)
----

Output

----
java.lang.Double
----

If two whole numbers or Long divides another Long, what you get is a Ratio in Clojure:

[source, clojure]
----
(type (/ 84 32))
----

Output

----
clojure.lang.Ratio
----

As you can see below stem:[84 / 32] in Clojure does not provide a decimal value, but outputs a Ratio:

[source, clojure]
----
(/ 84 32)
----

Output

----
21/8
----

You can convert one type of number to another, for example 32 is of type Long:

[source, clojure]
----
(type 32)
----

Output

----
java.lang.Long
----

But you can convert it to double by passing it to a `double` function as shown:

[source, clojure]
----
(double 32)
----

Output

----
32.0
----

When querying about its type, it does say Double:

[source, clojure]
----
(type (double 32))
----

Output

----
java.lang.Double
----

Say you don't want a division of two Long's to give you a Ratio as output, to prevent it, convert any one of the number that's been passed to `/` function into a Double as shown below:

[source, clojure]
----
(/ 84 (double 32))
----

Output

----
2.625
----

The output you get is a Double and not a Ratio:

[source, clojure]
----
(type (/ 84 (double 32)))
----

Output

----
java.lang.Double
----

If you want to just get a non-decimal part of a Double, pass that double to long function as shown:

[source, clojure]
----
(long 42.32)
----

Output

----
42
----

As you see, when a Double is passed to `long` function, it gets type cast to Long: 

[source, clojure]
----
(type (long 42.32))
----

Output

----
java.lang.Long
----
