== Why this book?

For unknown reason very smart programmers are using Clojure, I haven't figured out why. The writing of this book is to figure out why. My last job was in a medical coding company where we maintained 3 Rails app, I got to code in two of them, one had 0.1+ million lines of code, was headed by a guy who knew how to code and was maintained okay, other had 0.2+ million lines of code, had no test, headed by a guy who did not know how to code but could just do politics, that project prior to him was headed by people who did not know how to write maintainable software and senior developers in the project had to bear the brunt of history. It showed me how screwed Rails app can get if left unattended, so I want to search for something thats more idiot proof.

When I first met Ruby on Rails, I was very sure PHP will be the king of web page making, and it's true even today, but Rails changed my life and made me more productive. I will not say that with Rails we cannot handle massive projects, in my present job extremely skilled people and me are doing just that, but then this book is just a search, a very similar search I did in my PHP days when I got a hint of the power of Ruby, and this book is to document my search, if Clojure is good enough or not.

Another reason why I am going into Clojure is because of ClojureScript. If I can use the same language on both client and server side and if its not dreaded JavaScript, who wouldn't want to explore such language? Lisp seems to be a very old language and Clojure seems to be a Lisp dialect. Some how the inventors of Lisp seem to have struck the right balance early on, and I need to find out what it is.

I have lot of Data Science ideas, and looks like Clojure is fast and powerful enough to be used in those fields too. I want  to explore that too, though I wonder if JVM ever runs on GPU for fast computation.

One negative I find is JVM. Java is controlled by Oracle and its an evil enterprise like Microsoft and Apple. That's the only negative I have , but let's see how things go.